# frozen_string_literal: true

source "https://rubygems.org"

gemspec

group :development, :test do
  gem "rake",              require: false
  gem "rspec",   "~> 3.7", require: false
  gem "rubocop", "0.52.0", require: false
  gem "tjson",   "~> 0.5", require: false
end
